apiVersion: v1
kind: Service
metadata:
  labels:
    app: fdc3-identity-hackathon
  name: fdc3-identity-hackathon
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: fdc3
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fdc3-identity-hackathon
  type: NodePort
