const tickers = [
    'MRO',
    'MO',
    'ANET',
    'MTB',
    'CI',
    'CPT',
    'BIO',
    'XRAY',
    'VFC',
    'HSIC',
    'CTAS',
    'GE',
    'DHI',
    'JNPR',
    'KMB',
    'META',
    'EXPD',
    'WEC',
    'MKTX',
    'MCK',
    'AES',
    'MSFT',
    'CMCSA',
    'CMA',
    'FFIV',
    'KMX',
    'ESS',
    'TYL',
    'CTRA',
    'IVZ',
    'FOXA',
    'VICI',
    'EIX',
    'NRG',
    'CDW',
    'SJM',
    'INCY',
    'SEE',
    'KO',
    'CTLT',
    'CMG',
    'FE',
    'TTWO',
    'ES',
    'INTC',
    'OGN',
    'BAX',
    'TAP',
    'LRCX',
    'CRL',
    'NWSA',
    'AKAM',
    'ROP',
    'TECH',
    'DOV',
    'RL',
    'A',
    'ITW',
    'AAPL',
    'MLM',
    'DPZ',
    'PNC',
    'FTV',
    'REGN',
    'SWKS',
    'PAYX',
    'BKNG',
    'URI',
    'LYB',
    'MSCI',
    'FITB',
    'BBY',
    'EQT',
    'UHS',
    'SNPS',
    'AVY',
    'TEL',
    'GLW',
    'VTR',
    'PSA',
    'AWK',
    'AFL',
    'LLY',
    'BA',
    'ON',
    'WELL',
    'MPWR',
    'UNH',
    'CAH',
    'TSCO',
    'JCI',
    'EXR',
    'HPE',
    'PG',
    'BF.B',
    'EBAY',
    'EQR',
    'ENPH',
    'RE',
    'KEY',
    'EL',
    'GEN',
    'EPAM',
    'ISRG',
    'UDR',
    'PRU',
    'CEG',
    'TXN',
    'DG',
    'BR',
    'ADSK',
    'NCLH',
    'ETN',
    'TMO',
    'BIIB',
    'VMC',
    'KEYS',
    'MCD',
    'CSCO',
    'TSN',
    'EQIX',
    'PM',
    'PPL',
    'LUV',
    'SNA',
    'TDG',
    'MU',
    'ED',
    'PSX',
    'TFX',
    'AIZ',
    'TER',
    'DLTR',
    'IBM',
    'SBAC',
    'AMP',
    'BRO',
    'CB',
    'PYPL',
    'IRM',
    'VRSK',
    'LKQ',
    'BBWI',
    'RJF',
    'L',
    'GPN',
    'WAB',
    'MPC',
    'MNST',
    'NDAQ',
    'WY',
    'DE',
    'PKI',
    'INTU',
    'NVDA',
    'GNRC',
    'WTW',
    'VRTX',
    'MOS',
    'HRL',
    'XYL',
    'HUM',
    'PCAR',
    'NOC',
    'WHR',
    'O',
    'CARR',
    'STLD',
    'UAL',
    'EVRG',
    'CNP',
    'DVN',
    'BEN',
    'WFC',
    'PARA',
    'ETR',
    'MTCH',
    'MDLZ',
    'LOW',
    'AXP',
    'AEE',
    'AMD',
    'ADI',
    'AIG',
    'CTSH',
    'ALLE',
    'OKE',
    'SRE',
    'SEDG',
    'T',
    'MSI',
    'C',
    'BSX',
    'KDP',
    'PEG',
    'AON',
    'NTAP',
    'GOOG',
    'NFLX',
    'MA',
    'PFE',
    'DXCM',
    'ADP',
    'MOH',
    'PFG',
    'LMT',
    'ALL',
    'TGT',
    'YUM',
    'UPS',
    'MHK',
    'PXD',
    'COP',
    'AAP',
    'JNJ',
    'ORLY',
    'EXPE',
    'GL',
    'FSLR',
    'FIS',
    'MAA',
    'STX',
    'TMUS',
    'BKR',
    'DUK',
    'SBNY',
    'GPC',
    'FMC',
    'FTNT',
    'QRVO',
    'FLT',
    'ZBH',
    'DTE',
    'SBUX',
    'WDC',
    'NDSN',
    'AAL',
    'VTRS',
    'APH',
    'RMD',
    'ACN',
    'OTIS',
    'BRK.B',
    'TRV',
    'NI',
    'TRMB',
    'K',
    'ATO',
    'RTX',
    'LHX',
    'AZO',
    'IR',
    'IFF',
    'MAS',
    'ANSS',
    'MCO',
    'CLX',
    'ALB',
    'UNP',
    'MTD',
    'HBAN',
    'PKG',
    'DHR',
    'AVGO',
    'HAL',
    'FDX',
    'JPM',
    'HON',
    'LVS',
    'HES',
    'OXY',
    'DAL',
    'CZR',
    'TPR',
    'SWK',
    'DFS',
    'PWR',
    'AMZN',
    'HST',
    'MMM',
    'PHM',
    'CHD',
    'EXC',
    'BXP',
    'WYNN',
    'BK',
    'ODFL',
    'DOW',
    'VRSN',
    'MCHP',
    'GS',
    'LEN',
    'HLT',
    'IQV',
    'FISV',
    'TJX',
    'CCL',
    'VZ',
    'HCA',
    'NEE',
    'STZ',
    'PEAK',
    'AMGN',
    'ZTS',
    'AMT',
    'KIM',
    'NXPI',
    'IP',
    'SYK',
    'HOLX',
    'CE',
    'CMI',
    'AJG',
    'ROK',
    'PCG',
    'REG',
    'EA',
    'GD',
    'DRI',
    'HWM',
    'PH',
    'RSG',
    'PLD',
    'WMB',
    'DXC',
    'KR',
    'AMCR',
    'CSGP',
    'CF',
    'APA',
    'EW',
    'ZBRA',
    'SYY',
    'HII',
    'J',
    'APD',
    'GRMN',
    'DVA',
    'POOL',
    'MRK',
    'PAYC',
    'F',
    'IEX',
    'BALL',
    'NTRS',
    'ELV',
    'SPG',
    'SLB',
    'CINF',
    'GM',
    'DGX',
    'TFC',
    'GOOGL',
    'XOM',
    'CVX',
    'ULTA',
    'WBA',
    'IT',
    'BLK',
    'PPG',
    'QCOM',
    'XEL',
    'MGM',
    'TDY',
    'WMT',
    'MAR',
    'EOG',
    'MMC',
    'COF',
    'HPQ',
    'CBRE',
    'USB',
    'FAST',
    'CL',
    'WBD',
    'NOW',
    'CMS',
    'CFG',
    'CAT',
    'PGR',
    'MET',
    'FCX',
    'COST',
    'AVB',
    'WM',
    'PNR',
    'HSY',
    'JKHY',
    'CVS',
    'HD',
    'BDX',
    'CNC',
    'FOX',
    'CPRT',
    'ARE',
    'NWL',
    'SPGI',
    'MRNA',
    'GIS',
    'BAC',
    'ROST',
    'DLR',
    'CTVA',
    'LW',
    'CME',
    'PEP',
    'CHTR',
    'ILMN',
    'VLO',
    'CPB',
    'KLAC',
    'EFX',
    'EMR',
    'MKC',
    'CDNS',
    'CHRW',
    'FDS',
    'WRB',
    'LYV',
    'ADM',
    'SHW',
    'IPG',
    'SO',
    'SCHW',
    'BMY',
    'WAT',
    'AMAT',
    'CSX',
    'SIVB',
    'CRM',
    'COO',
    'LUMN',
    'WRK',
    'RCL',
    'ETSY',
    'NEM',
    'DISH',
    'ADBE',
    'STT',
    'ORCL',
    'NUE',
    'FANG',
    'EMN',
    'ABBV',
    'HAS',
    'DIS',
    'ALK',
    'NKE',
    'RHI',
    'RF',
    'AOS',
    'OMC',
    'NWS',
    'CAG',
    'APTV',
    'FRT',
    'TROW',
    'LDOS',
    'NSC',
    'PNW',
    'FRC',
    'IDXX',
    'WST',
    'LH',
    'STE',
    'GWW',
    'AME',
    'CDAY',
    'LNT',
    'ECL',
    'KMI',
    'V',
    'TSLA',
    'ABT',
    'LIN',
    'MS',
    'GILD',
    'MDT',
    'CCI',
    'ICE',
    'ATVI',
    'D',
    'KHC',
    'AEP',
    'TT',
    'DD',
    'ABC',
    'HIG',
    'ACGL',
    'INVH',
    'JBHT',
    'ROL',
    'ALGN',
    'TRGP',
    'NVR',
    'PTC',
    'SYF',
    'TXT',
    'CBOE',
    'BWA',
    'ZION',
    'LNC',
];
const names = [
    'Marathon Oil Corporation',
    'Altria Group, Inc.',
    'Arista Networks, Inc.',
    'M&T Bank Corporation',
    'Cigna Corporation',
    'Camden Property Trust',
    'Bio-Rad Laboratories, Inc.',
    'DENTSPLY SIRONA Inc.',
    'V.F. Corporation',
    'Henry Schein, Inc.',
    'Cintas Corporation',
    'General Electric Company',
    'D.R. Horton, Inc.',
    'Juniper Networks, Inc.',
    'Kimberly-Clark Corporation',
    'Meta Platforms, Inc.',
    'Expeditors International of Washington, Inc.',
    'WEC Energy Group, Inc.',
    'MarketAxess Holdings, Inc.',
    'McKesson Corporation',
    'The AES Corporation',
    'Microsoft Corporation',
    'Comcast Corporation',
    'Comerica Incorporated',
    'F5, Inc.',
    'CarMax Inc',
    'Essex Property Trust, Inc.',
    'Tyler Technologies, Inc.',
    'Coterra Energy Inc.',
    'Invesco Ltd',
    'Fox Corporation',
    'VICI Properties Inc.',
    'Edison International',
    'NRG Energy, Inc.',
    'CDW Corporation',
    'J.M. Smucker Company (The) New',
    'Incyte Corporation',
    'Sealed Air Corporation',
    'Coca-Cola Company (The)',
    'Catalent, Inc.',
    'Chipotle Mexican Grill, Inc.',
    'FirstEnergy Corp.',
    'Take-Two Interactive Software, Inc.',
    'Eversource Energy (D/B/A)',
    'Intel Corporation',
    'Organon & Co.',
    'Baxter International Inc.',
    'Molson Coors Beverage Company',
    'Lam Research Corporation',
    'Charles River Laboratories International, Inc.',
    'News Corporation',
    'Akamai Technologies, Inc.',
    'Roper Technologies, Inc.',
    'Bio-Techne Corp',
    'Dover Corporation',
    'Ralph Lauren Corporation',
    'Agilent Technologies, Inc.',
    'Illinois Tool Works Inc.',
    'Apple Inc.',
    'Martin Marietta Materials, Inc.',
    'Domino’s Pizza Inc',
    'PNC Financial Services Group, Inc. (The)',
    'Fortive Corporation',
    'Regeneron Pharmaceuticals, Inc.',
    'Skyworks Solutions, Inc.',
    'Paychex, Inc.',
    'Booking Holdings Inc. Common Stock',
    'United Rentals, Inc.',
    'LyondellBasell Industries NV',
    'MSCI Inc',
    'Fifth Third Bancorp',
    'Best Buy Co., Inc.',
    'EQT Corporation',
    'Universal Health Services, Inc.',
    'Synopsys, Inc.',
    'Avery Dennison Corporation',
    'TE Connectivity Ltd. New Switzerland Registered Shares',
    'Corning Incorporated',
    'Ventas, Inc.',
    'Public Storage',
    'American Water Works Company, Inc.',
    'AFLAC Incorporated',
    'Eli Lilly and Company',
    'Boeing Company (The)',
    'ON Semiconductor Corporation',
    'Welltower Inc.',
    'Monolithic Power Systems, Inc.',
    'UnitedHealth Group Incorporated',
    'Cardinal Health, Inc.',
    'Tractor Supply Company',
    'Johnson Controls International plc',
    'Extra Space Storage Inc',
    'Hewlett Packard Enterprise Company',
    'Procter & Gamble Company (The)',
    'Brown Forman Inc',
    'eBay Inc.',
    'Equity Residential',
    'Enphase Energy, Inc.',
    'Everest Re Group, Ltd.',
    'KeyCorp',
    'Estee Lauder Companies, Inc. (The)',
    'Gen Digital Inc.',
    'EPAM Systems, Inc.',
    'Intuitive Surgical, Inc.',
    'UDR, Inc.',
    'Prudential Financial, Inc.',
    'Constellation Energy Corporation',
    'Texas Instruments Incorporated',
    'Dollar General Corporation',
    'Broadridge Financial Solutions, Inc.',
    'Autodesk, Inc.',
    'Norwegian Cruise Line Holdings Ltd.',
    'Eaton Corporation, PLC',
    'Thermo Fisher Scientific Inc',
    'Biogen Inc.',
    'Vulcan Materials Company (Holding Company)',
    'Keysight Technologies Inc.',
    'McDonald’s Corporation',
    'Cisco Systems, Inc.',
    'Tyson Foods, Inc.',
    'Equinix, Inc.',
    'Philip Morris International Inc',
    'PPL Corporation',
    'Southwest Airlines Company',
    'Snap-On Incorporated',
    'Transdigm Group Inc.',
    'Micron Technology, Inc.',
    'Consolidated Edison, Inc.',
    'Phillips 66',
    'Teleflex Incorporated',
    'Assurant, Inc.',
    'Teradyne, Inc.',
    'Dollar Tree, Inc.',
    'International Business Machines Corporation',
    'SBA Communications Corporation',
    'Ameriprise Financial, Inc.',
    'Brown & Brown, Inc.',
    'Chubb Limited',
    'PayPal Holdings, Inc.',
    'Iron Mountain Incorporated (Delaware)',
    'Verisk Analytics, Inc.',
    'LKQ Corporation',
    'Bath & Body Works, Inc.',
    'Raymond James Financial, Inc.',
    'Loews Corporation',
    'Global Payments Inc.',
    'Westinghouse Air Brake Technologies Corporation',
    'Marathon Petroleum Corporation',
    'Monster Beverage Corporation',
    'Nasdaq, Inc.',
    'Weyerhaeuser Company',
    'Deere & Company',
    'PerkinElmer, Inc.',
    'Intuit Inc.',
    'NVIDIA Corporation',
    'Generac Holdlings Inc.',
    'Willis Towers Watson Public Limited Company',
    'Vertex Pharmaceuticals Incorporated',
    'Mosaic Company (The)',
    'Hormel Foods Corporation',
    'Xylem Inc.',
    'Humana Inc.',
    'PACCAR Inc.',
    'Northrop Grumman Corporation',
    'Whirlpool Corporation',
    'Realty Income Corporation',
    'Carrier Global Corporation',
    'Steel Dynamics, Inc.',
    'United Airlines Holdings, Inc.',
    'Evergy, Inc.',
    'CenterPoint Energy, Inc (Holding Co)',
    'Devon Energy Corporation',
    'Franklin Resources, Inc.',
    'Wells Fargo & Company',
    'Paramount Global',
    'Entergy Corporation',
    'Match Group, Inc.',
    'Mondelez International, Inc.',
    'Lowe’s Companies, Inc.',
    'American Express Company',
    'Ameren Corporation',
    'Advanced Micro Devices, Inc.',
    'Analog Devices, Inc.',
    'American International Group, Inc. New',
    'Cognizant Technology Solutions Corporation',
    'Allegion plc',
    'ONEOK, Inc.',
    'DBA Sempra',
    'SolarEdge Technologies, Inc.',
    'AT&T Inc.',
    'Motorola Solutions, Inc.',
    'Citigroup, Inc.',
    'Boston Scientific Corporation',
    'Keurig Dr Pepper Inc.',
    'Public Service Enterprise Group Incorporated',
    'Aon plc',
    'NetApp, Inc.',
    'Alphabet Inc.',
    'Netflix, Inc.',
    'Mastercard Incorporated',
    'Pfizer, Inc.',
    'DexCom, Inc.',
    'Automatic Data Processing, Inc.',
    'Molina Healthcare Inc',
    'Principal Financial Group Inc',
    'Lockheed Martin Corporation',
    'Allstate Corporation (The)',
    'Target Corporation',
    'Yum! Brands, Inc.',
    'United Parcel Service, Inc.',
    'Mohawk Industries, Inc.',
    'Pioneer Natural Resources Company',
    'ConocoPhillips',
    'Advance Auto Parts Inc.',
    'Johnson & Johnson',
    'O’Reilly Automotive, Inc.',
    'Expedia Group, Inc.',
    'Globe Life Inc.',
    'First Solar, Inc.',
    'Fidelity National Information Services, Inc.',
    'Mid-America Apartment Communities, Inc.',
    'Seagate Technology Holdings PLC',
    'T-Mobile US, Inc.',
    'Baker Hughes Company',
    'Duke Energy Corporation (Holding Company)',
    'Signature Bank',
    'Genuine Parts Company',
    'FMC Corporation',
    'Fortinet, Inc.',
    'Qorvo, Inc.',
    'FleetCor Technologies, Inc.',
    'Zimmer Biomet Holdings, Inc.',
    'DTE Energy Company',
    'Starbucks Corporation',
    'Western Digital Corporation',
    'Nordson Corporation',
    'American Airlines Group, Inc.',
    'Viatris Inc.',
    'Amphenol Corporation',
    'ResMed Inc.',
    'Accenture plc',
    'Otis Worldwide Corporation',
    'Berkshire Hathaway Inc. New',
    'The Travelers Companies, Inc.',
    'NiSource Inc',
    'Trimble Inc.',
    'Kellogg Company',
    'Atmos Energy Corporation',
    'Raytheon Technologies Corporation',
    'L3Harris Technologies, Inc.',
    'AutoZone, Inc.',
    'Ingersoll Rand Inc.',
    'International Flavors & Fragrances, Inc.',
    'Masco Corporation',
    'ANSYS, Inc.',
    'Moody’s Corporation',
    'Clorox Company (The)',
    'Albemarle Corporation',
    'Union Pacific Corporation',
    'Mettler-Toledo International, Inc.',
    'Huntington Bancshares Incorporated',
    'Packaging Corporation of America',
    'Danaher Corporation',
    'Broadcom Inc.',
    'Halliburton Company',
    'FedEx Corporation',
    'JP Morgan Chase & Co.',
    'Honeywell International Inc.',
    'Las Vegas Sands Corp.',
    'Hess Corporation',
    'Occidental Petroleum Corporation',
    'Delta Air Lines, Inc.',
    'Caesars Entertainment, Inc.',
    'Tapestry, Inc.',
    'Stanley Black & Decker, Inc.',
    'Discover Financial Services',
    'Quanta Services, Inc.',
    'Amazon.com, Inc.',
    'Host Hotels',
    '3M Company',
    'PulteGroup, Inc.',
    'Church & Dwight Company, Inc.',
    'Exelon Corporation',
    'Boston Properties, Inc.',
    'Wynn Resorts, Limited',
    'The Bank of New York Mellon Corporation',
    'Old Dominion Freight Line, Inc.',
    'Dow Inc.',
    'VeriSign, Inc.',
    'Microchip Technology Incorporated',
    'Goldman Sachs Group, Inc. (The)',
    'Lennar Corporation',
    'Hilton Worldwide Holdings Inc.',
    'IQVIA Holdings, Inc.',
    'Fiserv, Inc.',
    'TJX Companies, Inc. (The)',
    'Carnival Corporation',
    'Verizon Communications Inc.',
    'HCA Healthcare, Inc.',
    'NextEra Energy, Inc.',
    'Constellation Brands, Inc.',
    'Healthpeak Properties, Inc.',
    'Amgen Inc.',
    'Zoetis Inc.',
    'American Tower Corporation (REIT)',
    'Kimco Realty Corporation (HC)',
    'NXP Semiconductors N.V.',
    'International Paper Company',
    'Stryker Corporation',
    'Hologic, Inc.',
    'Celanese Corporation Celanese Corporation',
    'Cummins Inc.',
    'Arthur J. Gallagher & Co.',
    'Rockwell Automation, Inc.',
    'Pacific Gas & Electric Co.',
    'Regency Centers Corporation',
    'Electronic Arts Inc.',
    'General Dynamics Corporation',
    'Darden Restaurants, Inc.',
    'Howmet Aerospace Inc.',
    'Parker-Hannifin Corporation',
    'Republic Services, Inc.',
    'Prologis, Inc.',
    'Williams Companies, Inc. (The)',
    'DXC Technology Company',
    'Kroger Company (The)',
    'Amcor plc',
    'CoStar Group, Inc.',
    'CF Industries Holdings, Inc.',
    'APA Corporation',
    'Edwards Lifesciences Corporation',
    'Zebra Technologies Corporation',
    'Sysco Corporation',
    'Huntington Ingalls Industries, Inc.',
    'Jacobs Solutions Inc.',
    'Air Products and Chemicals, Inc.',
    'Garmin Ltd.',
    'DaVita Inc.',
    'Pool Corporation',
    'Merck & Company, Inc.',
    'Paycom Software, Inc.',
    'Ford Motor Company',
    'IDEX Corporation',
    'Ball Corporation',
    'Northern Trust Corporation',
    'Elevance Health, Inc.',
    'Simon Property Group, Inc.',
    'Schlumberger N.V.',
    'Cincinnati Financial Corporation',
    'General Motors Company',
    'Quest Diagnostics Incorporated',
    'Truist Financial Corporation',
    'Alphabet Inc.',
    'Exxon Mobil Corporation',
    'Chevron Corporation',
    'Ulta Beauty, Inc.',
    'Walgreens Boots Alliance, Inc.',
    'Gartner, Inc.',
    'BlackRock, Inc.',
    'PPG Industries, Inc.',
    'QUALCOMM Incorporated',
    'Xcel Energy Inc.',
    'MGM Resorts International',
    'Teledyne Technologies Incorporated',
    'Walmart Inc.',
    'Marriott International',
    'EOG Resources, Inc.',
    'Marsh & McLennan Companies, Inc.',
    'Capital One Financial Corporation',
    'HP Inc.',
    'CBRE Group Inc',
    'U.S. Bancorp',
    'Fastenal Company',
    'Colgate-Palmolive Company',
    'Warner Bros. Discovery, Inc. – Series A',
    'ServiceNow, Inc.',
    'CMS Energy Corporation',
    'Citizens Financial Group, Inc.',
    'Caterpillar, Inc.',
    'Progressive Corporation (The)',
    'MetLife, Inc.',
    'Freeport-McMoRan, Inc.',
    'Costco Wholesale Corporation',
    'AvalonBay Communities, Inc.',
    'Waste Management, Inc.',
    'Pentair plc.',
    'The Hershey Company',
    'Jack Henry & Associates, Inc.',
    'CVS Health Corporation',
    'Home Depot, Inc. (The)',
    'Becton, Dickinson and Company',
    'Centene Corporation',
    'Fox Corporation',
    'Copart, Inc.',
    'Alexandria Real Estate Equities, Inc.',
    'Newell Brands Inc.',
    'S&P Global Inc.',
    'Moderna, Inc.',
    'General Mills, Inc.',
    'Bank of America Corporation',
    'Ross Stores, Inc.',
    'Digital Realty Trust, Inc.',
    'Corteva, Inc.',
    'Lamb Weston Holdings, Inc.',
    'CME Group Inc.',
    'PepsiCo, Inc.',
    'Charter Communications, Inc.',
    'Illumina, Inc.',
    'Valero Energy Corporation',
    'Campbell Soup Company',
    'KLA Corporation',
    'Equifax, Inc.',
    'Emerson Electric Company',
    'McCormick & Company, Incorporated',
    'Cadence Design Systems, Inc.',
    'C.H. Robinson Worldwide, Inc.',
    'FactSet Research Systems Inc.',
    'W.R. Berkley Corporation',
    'Live Nation Entertainment, Inc.',
    'Archer-Daniels-Midland Company',
    'Sherwin-Williams Company (The)',
    'Interpublic Group of Companies, Inc. (The)',
    'Southern Company (The)',
    'Charles Schwab Corporation (The)',
    'Bristol-Myers Squibb Company',
    'Waters Corporation',
    'Applied Materials, Inc.',
    'CSX Corporation',
    'SVB Financial Group',
    'Salesforce, Inc.',
    'The Cooper Companies, Inc.',
    'Lumen Technologies, Inc.',
    'Westrock Company',
    'D/B/A Royal Caribbean Cruises Ltd.',
    'Etsy, Inc.',
    'Newmont Corporation',
    'DISH Network Corporation',
    'Adobe Inc.',
    'State Street Corporation',
    'Oracle Corporation',
    'Nucor Corporation',
    'Diamondback Energy, Inc.',
    'Eastman Chemical Company',
    'AbbVie Inc.',
    'Hasbro, Inc.',
    'Walt Disney Company (The)',
    'Alaska Air Group, Inc.',
    'Nike, Inc.',
    'Robert Half International Inc.',
    'Regions Financial Corporation',
    'A.O. Smith Corporation',
    'Omnicom Group Inc.',
    'News Corporation',
    'ConAgra Brands, Inc.',
    'Aptiv PLC',
    'Federal Realty Investment Trust',
    'T. Rowe Price Group, Inc.',
    'Leidos Holdings, Inc.',
    'Norfolk Southern Corporation',
    'Pinnacle West Capital Corporation',
    'FIRST REPUBLIC BANK',
    'IDEXX Laboratories, Inc.',
    'West Pharmaceutical Services, Inc.',
    'Laboratory Corporation of America Holdings',
    'STERIS plc (Ireland)',
    'W.W. Grainger, Inc.',
    'AMETEK, Inc.',
    'Ceridian HCM Holding Inc.',
    'Alliant Energy Corporation',
    'Ecolab Inc.',
    'Kinder Morgan, Inc.',
    'Visa Inc.',
    'Tesla, Inc.',
    'Abbott Laboratories',
    'Linde plc',
    'Morgan Stanley',
    'Gilead Sciences, Inc.',
    'Medtronic plc.',
    'Crown Castle Inc.',
    'Intercontinental Exchange Inc.',
    'Activision Blizzard, Inc',
    'Dominion Energy, Inc.',
    'The Kraft Heinz Company',
    'American Electric Power Company, Inc.',
    'Trane Technologies plc',
    'DuPont de Nemours, Inc.',
    'AmerisourceBergen Corporation',
    'Hartford Financial Services Group, Inc. (The)',
    'Arch Capital Group Ltd.',
    'Invitation Homes Inc.',
    'J.B. Hunt Transport Services, Inc.',
    'Rollins, Inc.',
    'Align Technology, Inc.',
    'Targa Resources, Inc.',
    'NVR, Inc.',
    'PTC Inc.',
    'Synchrony Financial',
    'Textron Inc.',
    'Cboe Global Markets, Inc.',
    'BorgWarner Inc.',
    'Zions Bancorporation N.A.',
    'Lincoln National Corporation',
];
const sectors = [
    'Energy Minerals',
    'Consumer Non-Durables',
    'Electronic Technology',
    'Finance',
    'Health Services',
    'Finance',
    'Health Technology',
    'Health Technology',
    'Consumer Non-Durables',
    'Distribution Services',
    'Consumer Services',
    'Producer Manufacturing',
    'Consumer Durables',
    'Electronic Technology',
    'Consumer Non-Durables',
    'Technology Services',
    'Transportation',
    'Utilities',
    'Finance',
    'Distribution Services',
    'Utilities',
    'Technology Services',
    'Consumer Services',
    'Finance',
    'Technology Services',
    'Retail Trade',
    'Finance',
    'Technology Services',
    'Energy Minerals',
    'Finance',
    'Consumer Services',
    'Finance',
    'Utilities',
    'Utilities',
    'Technology Services',
    'Consumer Non-Durables',
    'Health Technology',
    'Process Industries',
    'Consumer Non-Durables',
    'Health Technology',
    'Consumer Services',
    'Utilities',
    'Technology Services',
    'Utilities',
    'Electronic Technology',
    'Health Technology',
    'Health Technology',
    'Consumer Non-Durables',
    'Producer Manufacturing',
    'Commercial Services',
    'Consumer Services',
    'Technology Services',
    'Technology Services',
    'Health Technology',
    'Producer Manufacturing',
    'Distribution Services',
    'Health Technology',
    'Producer Manufacturing',
    'Electronic Technology',
    'Non-Energy Minerals',
    'Consumer Services',
    'Finance',
    'Electronic Technology',
    'Health Technology',
    'Electronic Technology',
    'Technology Services',
    'Consumer Services',
    'Finance',
    'Process Industries',
    'Technology Services',
    'Finance',
    'Retail Trade',
    'Energy Minerals',
    'Health Services',
    'Technology Services',
    'Process Industries',
    'Electronic Technology',
    'Electronic Technology',
    'Finance',
    'Finance',
    'Utilities',
    'Finance',
    'Health Technology',
    'Electronic Technology',
    'Electronic Technology',
    'Finance',
    'Electronic Technology',
    'Health Services',
    'Distribution Services',
    'Retail Trade',
    'Producer Manufacturing',
    'Finance',
    'Electronic Technology',
    'Consumer Non-Durables',
    'Consumer Non-Durables',
    'Retail Trade',
    'Finance',
    'Electronic Technology',
    'Finance',
    'Finance',
    'Consumer Non-Durables',
    'Technology Services',
    'Technology Services',
    'Health Technology',
    'Finance',
    'Finance',
    'Utilities',
    'Electronic Technology',
    'Retail Trade',
    'Technology Services',
    'Technology Services',
    'Consumer Services',
    'Producer Manufacturing',
    'Health Technology',
    'Health Technology',
    'Non-Energy Minerals',
    'Electronic Technology',
    'Consumer Services',
    'Electronic Technology',
    'Consumer Non-Durables',
    'Technology Services',
    'Consumer Non-Durables',
    'Utilities',
    'Transportation',
    'Consumer Durables',
    'Electronic Technology',
    'Electronic Technology',
    'Utilities',
    'Energy Minerals',
    'Health Technology',
    'Finance',
    'Electronic Technology',
    'Retail Trade',
    'Technology Services',
    'Finance',
    'Finance',
    'Finance',
    'Finance',
    'Commercial Services',
    'Finance',
    'Technology Services',
    'Consumer Durables',
    'Retail Trade',
    'Finance',
    'Finance',
    'Commercial Services',
    'Producer Manufacturing',
    'Energy Minerals',
    'Consumer Non-Durables',
    'Finance',
    'Finance',
    'Producer Manufacturing',
    'Health Technology',
    'Technology Services',
    'Electronic Technology',
    'Producer Manufacturing',
    'Finance',
    'Health Technology',
    'Process Industries',
    'Consumer Non-Durables',
    'Producer Manufacturing',
    'Health Services',
    'Producer Manufacturing',
    'Electronic Technology',
    'Consumer Durables',
    'Finance',
    'Producer Manufacturing',
    'Non-Energy Minerals',
    'Transportation',
    'Utilities',
    'Utilities',
    'Energy Minerals',
    'Finance',
    'Finance',
    'Consumer Services',
    'Utilities',
    'Technology Services',
    'Consumer Non-Durables',
    'Retail Trade',
    'Finance',
    'Utilities',
    'Electronic Technology',
    'Electronic Technology',
    'Finance',
    'Technology Services',
    'Producer Manufacturing',
    'Industrial Services',
    'Utilities',
    'Producer Manufacturing',
    'Communications',
    'Electronic Technology',
    'Finance',
    'Distribution Services',
    'Consumer Non-Durables',
    'Utilities',
    'Finance',
    'Electronic Technology',
    'Technology Services',
    'Technology Services',
    'Commercial Services',
    'Health Technology',
    'Health Technology',
    'Technology Services',
    'Health Services',
    'Finance',
    'Electronic Technology',
    'Finance',
    'Retail Trade',
    'Consumer Services',
    'Transportation',
    'Non-Energy Minerals',
    'Energy Minerals',
    'Energy Minerals',
    'Retail Trade',
    'Health Technology',
    'Retail Trade',
    'Consumer Services',
    'Finance',
    'Electronic Technology',
    'Commercial Services',
    'Finance',
    'Electronic Technology',
    'Communications',
    'Industrial Services',
    'Utilities',
    'Finance',
    'Distribution Services',
    'Process Industries',
    'Electronic Technology',
    'Electronic Technology',
    'Commercial Services',
    'Health Technology',
    'Utilities',
    'Consumer Services',
    'Electronic Technology',
    'Producer Manufacturing',
    'Transportation',
    'Health Technology',
    'Electronic Technology',
    'Health Technology',
    'Technology Services',
    'Producer Manufacturing',
    'Finance',
    'Finance',
    'Utilities',
    'Electronic Technology',
    'Consumer Non-Durables',
    'Utilities',
    'Electronic Technology',
    'Electronic Technology',
    'Retail Trade',
    'Producer Manufacturing',
    'Consumer Non-Durables',
    'Producer Manufacturing',
    'Technology Services',
    'Commercial Services',
    'Consumer Non-Durables',
    'Process Industries',
    'Transportation',
    'Health Technology',
    'Finance',
    'Process Industries',
    'Health Technology',
    'Electronic Technology',
    'Energy Minerals',
    'Transportation',
    'Finance',
    'Electronic Technology',
    'Consumer Services',
    'Energy Minerals',
    'Energy Minerals',
    'Transportation',
    'Consumer Services',
    'Retail Trade',
    'Consumer Durables',
    'Finance',
    'Industrial Services',
    'Retail Trade',
    'Finance',
    'Health Technology',
    'Consumer Durables',
    'Consumer Non-Durables',
    'Utilities',
    'Finance',
    'Consumer Services',
    'Finance',
    'Transportation',
    'Process Industries',
    'Technology Services',
    'Electronic Technology',
    'Finance',
    'Consumer Durables',
    'Consumer Services',
    'Health Services',
    'Finance',
    'Retail Trade',
    'Consumer Services',
    'Communications',
    'Health Services',
    'Utilities',
    'Consumer Non-Durables',
    'Finance',
    'Health Technology',
    'Health Technology',
    'Finance',
    'Finance',
    'Electronic Technology',
    'Process Industries',
    'Health Technology',
    'Health Technology',
    'Process Industries',
    'Producer Manufacturing',
    'Finance',
    'Electronic Technology',
    'Utilities',
    'Finance',
    'Technology Services',
    'Electronic Technology',
    'Consumer Services',
    'Electronic Technology',
    'Producer Manufacturing',
    'Industrial Services',
    'Finance',
    'Energy Minerals',
    'Technology Services',
    'Retail Trade',
    'Process Industries',
    'Technology Services',
    'Process Industries',
    'Energy Minerals',
    'Health Technology',
    'Electronic Technology',
    'Transportation',
    'Electronic Technology',
    'Industrial Services',
    'Process Industries',
    'Electronic Technology',
    'Health Services',
    'Distribution Services',
    'Health Technology',
    'Technology Services',
    'Consumer Durables',
    'Producer Manufacturing',
    'Process Industries',
    'Finance',
    'Health Services',
    'Finance',
    'Industrial Services',
    'Finance',
    'Consumer Durables',
    'Health Services',
    'Finance',
    'Technology Services',
    'Energy Minerals',
    'Energy Minerals',
    'Retail Trade',
    'Retail Trade',
    'Technology Services',
    'Finance',
    'Process Industries',
    'Electronic Technology',
    'Utilities',
    'Consumer Services',
    'Electronic Technology',
    'Retail Trade',
    'Consumer Services',
    'Energy Minerals',
    'Finance',
    'Finance',
    'Electronic Technology',
    'Finance',
    'Finance',
    'Distribution Services',
    'Consumer Non-Durables',
    'Consumer Services',
    'Technology Services',
    'Utilities',
    'Finance',
    'Producer Manufacturing',
    'Finance',
    'Finance',
    'Non-Energy Minerals',
    'Retail Trade',
    'Finance',
    'Industrial Services',
    'Producer Manufacturing',
    'Consumer Non-Durables',
    'Technology Services',
    'Retail Trade',
    'Retail Trade',
    'Health Technology',
    'Health Services',
    'Consumer Services',
    'Commercial Services',
    'Finance',
    'Producer Manufacturing',
    'Commercial Services',
    'Health Technology',
    'Consumer Non-Durables',
    'Finance',
    'Retail Trade',
    'Finance',
    'Process Industries',
    'Consumer Non-Durables',
    'Finance',
    'Consumer Non-Durables',
    'Consumer Services',
    'Health Technology',
    'Energy Minerals',
    'Consumer Non-Durables',
    'Electronic Technology',
    'Commercial Services',
    'Electronic Technology',
    'Consumer Non-Durables',
    'Technology Services',
    'Transportation',
    'Technology Services',
    'Finance',
    'Consumer Services',
    'Process Industries',
    'Process Industries',
    'Commercial Services',
    'Utilities',
    'Finance',
    'Health Technology',
    'Health Technology',
    'Producer Manufacturing',
    'Transportation',
    'Finance',
    'Technology Services',
    'Health Technology',
    'Communications',
    'Process Industries',
    'Consumer Services',
    'Retail Trade',
    'Non-Energy Minerals',
    'Consumer Services',
    'Technology Services',
    'Finance',
    'Technology Services',
    'Non-Energy Minerals',
    'Energy Minerals',
    'Process Industries',
    'Health Technology',
    'Consumer Durables',
    'Consumer Services',
    'Transportation',
    'Consumer Non-Durables',
    'Commercial Services',
    'Finance',
    'Producer Manufacturing',
    'Commercial Services',
    'Consumer Services',
    'Consumer Non-Durables',
    'Producer Manufacturing',
    'Finance',
    'Finance',
    'Electronic Technology',
    'Transportation',
    'Utilities',
    'Finance',
    'Health Technology',
    'Health Technology',
    'Health Services',
    'Health Technology',
    'Distribution Services',
    'Producer Manufacturing',
    'Technology Services',
    'Utilities',
    'Process Industries',
    'Industrial Services',
    'Commercial Services',
    'Consumer Durables',
    'Health Technology',
    'Process Industries',
    'Finance',
    'Health Technology',
    'Health Technology',
    'Finance',
    'Finance',
    'Technology Services',
    'Utilities',
    'Consumer Non-Durables',
    'Utilities',
    'Producer Manufacturing',
    'Process Industries',
    'Distribution Services',
    'Finance',
    'Finance',
    'Finance',
    'Transportation',
    'Consumer Services',
    'Health Technology',
    'Utilities',
    'Consumer Durables',
    'Technology Services',
    'Finance',
    'Electronic Technology',
    'Finance',
    'Producer Manufacturing',
    'Finance',
    'Finance',
];

const randomPosition = () => Math.floor(Math.random() * 10000);

const data = {
    'Ticker': tickers,
    'Name': names,
    'Sector': sectors,
    'Position': [],
    'Last Done': [],
    'Change': [],
    'MTM Value': [],
};

tickers.forEach(t => {
    data['Position'].push(randomPosition());
    data['Last Done'].push(0.01 * randomPosition());
    data['Change'].push((Math.random() > 0.5 ? 1 : -1) * 0.001 * randomPosition());
    data['MTM Value'].push(randomPosition() / 100 * randomPosition());
});

export default data;
