name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: web/yarn.lock
          registry-url: https://registry.npmjs.org

      - run: cd web && yarn install && yarn build && cp -r dist ../src/main/resources/static/

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - run: echo owner=$(echo "${{github.repository_owner}}" | tr 'A-Z' 'a-z') >>${GITHUB_ENV}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.owner }}/fdc3-hackathon:${{ steps.tag.outputs.new_tag }}

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.UAT_GKE_AUTH }}

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.UAT_GKE_CLUSTER }}
          location: ${{ secrets.UAT_GKE_ZONE }}

      - env:
          DEPLOYMENT: ${{ github.event.repository.name }}
          IMAGE_TAG: ghcr.io/${{ env.owner }}/fdc3-hackathon:${{ steps.tag.outputs.new_tag }}
        run: |
          kubectl set image deployment/${DEPLOYMENT} fdc3-hackathon=${IMAGE_TAG}
          kubectl rollout status deployment/${DEPLOYMENT}
